name: Release YeeLight Lightstrip Pro Controller

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Extract release notes
        id: extract_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Write release notes to file
        run: echo "$RELEASE_NOTES" > extracted_notes.txt
        env:
          RELEASE_NOTES: ${{ steps.extract_notes.outputs.release_notes }}

      - name: Build and Publish macOS App
        run: npm run build:mac -- --publish always -c.releaseInfo.releaseNotesFile="extracted_notes.txt"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
